# Generated by Django 3.0.7 on 2020-08-19 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='start_price',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
