# Generated by Django 3.0.7 on 2020-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200819_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(max_length=10)),
                ('bidder', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('listing', models.ManyToManyField(related_name='bids', to='auctions.Listing')),
            ],
        ),
    ]
