# Generated by Django 3.0.7 on 2020-08-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
