# Generated by Django 3.0.7 on 2020-08-20 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200820_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 21, 41, 53, 59319)),
            preserve_default=False,
        ),
    ]
