# Generated by Django 3.0.7 on 2020-08-21 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watching_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
