# Generated by Django 3.0.7 on 2020-08-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200821_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.FloatField(max_length=10),
        ),
    ]
